//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiTraSua.CSDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MaHD { get; set; }
        public int MaBan { get; set; }
        public string MaMon { get; set; }
        public string Size { get; set; }
        public int Soluong { get; set; }
        public decimal DonGia { get; set; }
    
        public virtual BAN BAN { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
